version: '3.8'

services:
  # 1. Database Service (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: cafe_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - cafe_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env

  # 2. Backend Service (Spring Boot)
  backend:
    build: .
    container_name: cafe_backend
    ports:
      - "8080:8080"
    environment:
      # Ghi đè cấu hình trong application.yaml để trỏ DB sang container 'db' thay vì localhost
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

# Khai báo Volume để lưu trữ dữ liệu DB không bị mất khi xóa container
volumes:
  cafe_pgdata:
